version: "3.8"
services:
    dozzle:
        container_name: dozzle
        image: amir20/dozzle:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 9999:8080
        restart: always
    php:
        build:
            context: './php/'
            args:
                PHP_VERSION: ${PHP_VERSION}
        networks:
            - backend
        volumes:
            - ${PROJECT_ROOT}/:/var/www/html/
        container_name: php
        restart: always
    apache:
        build:
            context: './apache/'
            args:
                APACHE_VERSION: ${APACHE_VERSION}
        depends_on:
            - php
            - db
        networks:
            - frontend
            - backend
        ports:
            - "9593:80"
        volumes:
            - ${PROJECT_ROOT}/:/var/www/html/
        container_name: apache
        restart: always

    db:
        build:
            context: './db/'
            args:
                MYSQL_VERSION: ${MYSQL_VERSION}
                MYSQL_ROOT_PASSWORD: somephpbb
                MYSQL_DATABASE: phpbb
                MYSQL_USER: phpbb
                MYSQL_PASSWORD: phpbb
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - frontend
            - backend
        container_name: db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somephpbb
            MYSQL_DATABASE: phpbb
            MYSQL_USER: phpbb
            MYSQL_PASSWORD: phpbb
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8181:80
        networks:
            - frontend
            - backend
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_ARBITRARY: 1
            # PMA_USER: root
            # PMA_PASSWORD: somephpbb
networks:
    frontend:
    backend:
volumes:
    db_data: {}
